---
title: "Data Simulation"
author: "Claire Powers"
date: "2025-01-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())

# Packages
library(tidyverse)
library(parallel)
library(doParallel)
library(foreach)
library(EnvStats)

# Plotting
theme_set(theme_bw(base_size=14))
stage.cols = c(seed="springgreen4",juv="blue3",flrg="magenta3")
place.cols = c(Cool ="#175D71" , Warm = "#98463C", Avg = "#D48B47")

# Constants
sizes = c(seed=1,juv=8,flrg=10)

# Functions 
source("ModelFunctions/ParamVals.R")
source("ModelFunctions/logit2prob.R")
source("ModelFunctions/survival_fun.R")
source("ModelFunctions/growth_fun.R")
source("ModelFunctions/subpop_mx_fun.R")
source("ModelFunctions/seednum_fun.R")
source("SimFunctions/moveMx_fun.R")
source("ModelFunctions/SimulateDataFun.R")
```


```{r}

# Simulate data
simulated_data <- simulate_population(surv_params, growth_params, seeds.in=5, num_individuals = 10, timesteps = 50, clim.sd = 1,asp.mag = 2,asp.effect = 1)

head(simulated_data$all_population)

sim_data <- simulated_data$all_population_data %>% 
  group_by(timestep,stage) %>% 
  summarize(counts = sum(survival_status),
            total = sum(counts))


ggplot(sim_data, aes(x = timestep, y = counts,color = stage)) +
  geom_point() 

```

