---
title: "Simulated data analysis"
author: "Claire Powers"
date: "2025-02-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
rm(list=ls())
library(tidyverse)
library(vroom)
library(lme4)
library(ggthemes)
library(EnvStats)
```

# Read in data
- V1 = aspect effects (-1,1)
```{r read_data}
clims <- c(2,10,15)
asp.mags <- c(2,5,10)
move.rates <- c(0.05,0.2,0.4)
rho <- 0

for(i in 1:length(asp.mags)){
  for(j in 1:length(clims)){
   for(k in 1:length(move.rates)){
     
     tmp_data_fns <- list.files(paste0("SimOutput/simulatedData/V1/aspmag",asp.mags[i]),
                           pattern = paste0("clim",clims[j],"_rho",rho,"_move",move.rates[k]),
                           full.names = T)
     
     tmp_data <- vroom::vroom(tmp_data_fns,
                              col_types = cols(
                                seeds = col_double()
                                )) %>%
       filter(timestep>0) %>%
       filter(!is.na(asp.mag)) %>% 
       mutate(region.clim = clim,
              subpop.clim = region.clim+asp.effect*asp.mag) %>% 
       select(-clim)
     
     df_name <- paste0("asp",asp.mags[i],"_clim",clims[j],"_move",move.rates[k])
     assign(df.name, tmp_data)
     rm(tmp_data,tmp_data_fns,df_name)
     
   } 
  }
}
```

### Looking at output to check pop numbers through time
```{r popSizePlots}
stage.nums <- sim_data %>% 
  filter(end.stage!="dead") %>% 
  group_by(timestep,stage = end.stage,rep,asp.effect) %>% 
  summarise(size = sum(survival_status,na.rm=T)) 

ggplot(stage.nums,aes(x=timestep,y=size,color=factor(stage)))+
  geom_point(aes(shape=factor(asp.effect)))+
  geom_line(aes(linetype=factor(asp.effect)))+
  ggh4x::facet_grid2(stage~rep, scales = "free_y", independent = "y")+
  theme_few(base_size = 14)+
  theme(panel.grid.major = element_line(colour = "grey90",linetype=3),
        panel.grid.minor = element_line(colour = "grey90",linetype=3))

pop.size <- sim_data %>% 
  group_by(timestep,rep) %>% 
  summarise(size=sum(survival_status,na.rm=T)) %>% 
  mutate(ann.lam = size/lag(size)) %>% 
  mutate(geo.mean = geoMean(ann.lam,na.rm=T))

subpop.sizes <- sim_data %>% 
  group_by(timestep,rep,asp.effect) %>% 
  summarise(size=sum(survival_status,na.rm=T)) %>% 
  mutate(ann.lam = size/lag(size))

ggplot()+
  geom_point(data=pop.size,aes(x=timestep,y=size))+
  geom_line(data=pop.size,aes(x=timestep,y=size))+
  geom_point(data=subpop.sizes,aes(x=timestep,y=size,color=factor(asp.effect)))+
  geom_line(data=subpop.sizes,aes(x=timestep,y=size,color=factor(asp.effect)))+
  theme_few(base_size = 15)+
  facet_wrap(~rep)

clim_data <- sim_data %>% 
  select(region.clim,asp.effect,subpop.clim,timestep,rep) %>% 
  unique() %>% 
  filter(!is.na(asp.effect))

clim_data <- clim_data %>% 
  pivot_wider(id_cols = c(timestep,rep,region.clim), names_from = asp.effect, values_from = subpop.clim, names_prefix = "sub")
head(clim_data)

ggplot(clim_data,aes(x=region.clim))+
  geom_point(aes(y=region.clim))+
  geom_point(aes(y=`sub-1`),color="blue")+
  geom_point(aes(y=sub1),color="red")+
  theme_minimal()

```


# Data processing
### Seeds
```{r seeds}

seed_df <- asp2_clim2_move0.2 %>% 
  filter(start.stage=="seed") %>% 
  mutate(size = 1)
head(seed_df)

surv_lm_subs <- glmer(survival_status~size + (region.clim + asp.mag*asp.effect) + (region.clim + asp.mag*asp.effect)^2 + (1|rep), family="binomial", data=seed_df)
surv_lm_all <- glmer(survival_status~size + region.clim + region.clim + (1|rep), family="binomial", data=seed_df)

predict_df <- expand.grid(size=1,
                          asp.mag=2,
                          asp.effect = c(-1,1),
                          region.clim = seq(min(seed_df$region.clim),max(seed_df$region.clim), length.out = 100)) %>% 
  mutate(subs_predict = predict(surv_lm_subs,newdata=predict_df,re.form=NA,type="response"),
         all_predict = predict(surv_lm_all,newdata=predict_df,re.form=NA,type="response"))


ggplot(predict_df,aes(x=region.clim))+
  geom_point(aes(y=subs_predict,shape=factor(asp.effect),color=factor(asp.effect)))+
  geom_point(aes(y=all_predict,shape = "pooled",color="pooled"))+
  theme_clean()
```



