---
title: "Setting up the simulation functions"
author: "Claire Powers"
date: "2024-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Set-up
```{r start}
rm(list=ls())

# Packages
library(tidyverse)
library(parallel)
library(doParallel)
library(foreach)
library(EnvStats)

# Functions & model parameters
source("SimFunctions/moveMx_fun.R")
source("SimFunctions/simfun_exp.R")
source("ModelFunctions/ParamVals.R")
source("ModelFunctions/subpop_mx_fun.R")
seeds_df <- read_csv("seedSearchOutput/seedSearch_2025-01-29 21:30:11.114866.csv") %>% 
  rbind(.,read_csv("seedSearchOutput/seedSearch_2025-02-07 14:15:25.516399.csv")) %>% 
  rbind(.,read_csv("seedSearchOutput/seedSearch_2025-02-11 21:16:56.112911.csv")) %>% 
  rbind(.,read_csv("seedSearchOutput/seedSearch_2025-02-17 10:07:58.468259.csv",
                   col_types = c(asp.effects=col_character()))) %>% 
  mutate(seeds2 = floor(seeds)) %>% 
  group_by(asp.effects,asp.mag,clim.sd) %>% 
  summarize(avg.seeds = round(mean(seeds)))
summary(seeds_df)

seeds_df$asp.effects[seeds_df$asp.effects=="-1.51"] = "-1.5,1"

```

## Run simulations for all aspect effect combinations
```{r Scen1}

# # Sim. function inputs
burn.in.yrs <- 100
sim.yrs <- 500
reps <- 5
clim.sds <- seq(0,25,by=1);clim.sds[clim.sds==0] <- 0.001
asp.mags <- seq(0,20,by=1)
rhos <- seq(0,0.5,0.1)
move.rates <- seq(0,0.2,0.05)
# 
# asp.effects <- 
#   list(
#     # Symmetrical
#     c(-1, 1), # Simple
#     c(-1.1,-1, 1,1.1), # More pops
#     c(-1.5,-1, 1,1.5), # More pops more dramatic
#     
#     # Asymmetrical
#     c(-1,-1,1),
#     c(-1.1,1) , 
#     c(-1.2,-1.1,-1,1)
# )
# 
# asp.effects <-
#   list(
#     c(-2, 1), 
#     c(-2,-1, 1), 
#     c(-2,-1, 1,2) 
# )
asp.effects <-
  list(
    c(-1.5, 1) # Simple
)

# Things needed to run sim function line by line
# clim.sd.i <- clim.sd <- 10
# asp.mag <- asp.mag.i <- 2
# rep = 1
# rho.i <- 0.5
# asp.eff.i = 1
# move.rate.i = 0.1

#### Run S1 #####
cl = makeCluster(spec = 20)
registerDoParallel(cl = cl)

S1_out_df <- foreach(rep = 1:reps, .combine = rbind,.packages=c("tidyverse","EnvStats")) %:% 
  foreach(asp.eff.i = 1:length(asp.effects), .combine = rbind,.packages=c("tidyverse","EnvStats")) %:%
    foreach(move.rate.i = move.rates, .combine = rbind,.packages=c("tidyverse","EnvStats")) %:%
      foreach(clim.sd.i = clim.sds, .combine = rbind,.packages=c("tidyverse","EnvStats")) %:%
        foreach(asp.mag.i = asp.mags, .combine = rbind,.packages=c("tidyverse","EnvStats")) %:% 
          foreach(rho.i = rhos,.combine = rbind,.packages=c("tidyverse","EnvStats")) %dopar% {

            asp.effects.i <- asp.effects[asp.eff.i] %>% unlist()
            n.subpops.i <- length(asp.effects.i)
            
            # move.rates.i <- move.rates.df[move.rates.row,]
          
            ##### Create a movement matrix from the move.rates row
            move.mx.i <- moveMx_fun(n.subpops.i,move.rate.i)
          
            seeds.i = seeds_df$avg.seeds[seeds_df$asp.mag==asp.mag.i & seeds_df$asp.effects == paste(asp.effects.i,collapse = ",")]
            
            
            df = simfun_exponential(burn.in.yrs=burn.in.yrs, sim.yrs=sim.yrs, n.subpops=n.subpops.i, asp.effects = asp.effects.i,
                                clim.sd=clim.sd.i, asp.mag=asp.mag.i, move.mx = move.mx.i,seeds = seeds.i,rho = rho.i)
            
            tmp.df = df %>%
              filter(year>burn.in.yrs) %>% # Filter out burn-in years. This could also happen within the function.
              summarise(clim.mean = mean(clim),
                        clim.var = var(clim),
                        pop.var = var(pop.lam),
                        lt.pop.lam = geoMean(pop.lam)) %>% 
              mutate(asp.effect = paste(asp.effects.i,collapse = ","),
                     asp.mag = asp.mag.i,
                     clim.sd = clim.sd.i,
                     rho = rho.i,
                     rep = rep,
                     move.rate = move.rate.i)
            return(tmp.df)
            # rm(df,tmp.df,clim.sd.i,asp.mag.i,move.rate.i)
        
      }
stopCluster(cl)
# S1_out_df <- rename(S1_out_df,move.rate=y)
S1_out_df$asp.effect <- paste0("c(",S1_out_df$asp.effect,")")
write_csv(S1_out_df,paste0("SimOutput/S1_",round(Sys.time()),".csv"))
```

S1 Deep dive
```{r s1.deepdive}

# Sim. function inputs
burn.in.yrs <- 100
sim.yrs <- 500
asp.effects <- c(-1,1)
n.subpops <- length(asp.effects)
reps <- 5
clim.sds <- seq(0,10,by=1);clim.sds[clim.sds==0] <- 0.001
asp.mags <- 20
rhos <- 0

## Creating all combinations of movement rates
subpop.names = LETTERS[1:n.subpops] # Name subpops with letters
move.rates = 0.025
move.dirs = expand.grid(from=subpop.names,to=subpop.names) %>% # get all combos
  # Remove rows that imply no movement (A to A)
  filter(from!=to) %>% 
   # Concatenate
  mutate(col.names = paste0(from,"to",to)) %>% 
  # save last column as a vector
  arrange(col.names) %>% pull() 

# Create movement data.frame to loop over
move.rates.df = matrix(data=rep(move.rates,length(move.dirs)),ncol=length(move.dirs)) %>% # generate matrix with movement rates
  as.data.frame() %>% 
  # Make all combos of movement rates
  expand.grid() %>% 
  filter(if_all(starts_with("V"),~ .==V1)) ## This filters for symmetrical movement rates
names(move.rates.df)=move.dirs # rename columns to make movement direction clear
rm(subpop.names,move.dirs,move.rates) # remove extra things from env

#### Run S1 #####
cl = makeCluster(5)
registerDoParallel(cl = cl)

S1_out_df <- foreach(rep = 1:reps, .combine = rbind,.packages=c("tidyverse","EnvStats")) %:% 
  foreach(move.rates.row = 1:nrow(move.rates.df), .combine = rbind,.packages=c("tidyverse","EnvStats")) %:%
    foreach(clim.sd.i = clim.sds, .combine = rbind,.packages=c("tidyverse","EnvStats")) %:%
      foreach(asp.mag.i = asp.mags, .combine = rbind,.packages=c("tidyverse","EnvStats")) %:% 
        foreach(rho.i = rhos,.combine = rbind,.packages=c("tidyverse","EnvStats")) %dopar% {

        move.rates.i <- move.rates.df[move.rates.row,]
        
        ##### Create a movement matrix from the move.rates row
        move.mx.i <- moveMx_fun(n.subpops,move.rates.i)
        
        seeds.i = seeds_df$avg.seeds[seeds_df$asp.mag==asp.mag.i]
        
        df = simfun_exponential(burn.in.yrs=burn.in.yrs, sim.yrs=sim.yrs, n.subpops=n.subpops,asp.effects = asp.effects,
                            clim.sd=clim.sd.i, asp.mag=asp.mag.i, move.mx = move.mx.i,seeds = seeds.i,rho = rho.i)
        
        df = df %>%
          filter(year>burn.in.yrs) %>% # Filter out burn-in years. This could also happen within the function.
          mutate(clim.sd = clim.sd.i,
                 rho = rho.i,
                 asp.mag = asp.mag.i,
                 rep = rep,
                 move.rate = move.rates.df$AtoB[1])
        return(df)
        # rm(df,tmp.df,clim.sd.i,asp.mag.i,move.rate.i)
        
      }
stopCluster(cl)
# write_csv(S1_out_df,paste0("SimOutput/S1_deepDive_",round(Sys.time()),".csv"))
```

```{r}
# Sim. function inputs
burn.in.yrs <- 100
sim.yrs <- 300
asp.effects.i <- c(-1,0,1)
n.subpops.i <- length(asp.effects.i)
move.rate.i <- 0.05
asp.mag.i <- 10
clim.sd.i <- 10
rho.i = 0

##### Create a movement matrix from the move.rates row
move.mx.i <- moveMx_fun(n.subpops.i,move.rate.i)

seeds.i = seeds_df$avg.seeds[seeds_df$asp.mag==asp.mag.i & seeds_df$asp.effects == paste(asp.effects.i,collapse = ",")]

df.rnorm = simfun_exponential(burn.in.yrs=burn.in.yrs, sim.yrs=sim.yrs, n.subpops=n.subpops.i, asp.effects = asp.effects.i,
                    clim.sd=clim.sd.i, asp.mag=asp.mag.i, move.mx = move.mx.i,seeds = seeds.i,rho = rho.i)

df.rnorm = filter(df.rnorm,year>burn.in.yrs)
ggplot(df.rnorm,aes(x=clim))+
  geom_line(aes(y=`s_-1`,color="s-1"))+
  geom_line(aes(y=`s_0`,color="s0"))+
  geom_line(aes(y=`s_1`,color="s1"))+
  geom_point(aes(y=pop.lam,color="pop"))+
  theme_classic()


df.unif = simfun_exponential(burn.in.yrs=burn.in.yrs, sim.yrs=sim.yrs, n.subpops=n.subpops.i, asp.effects = asp.effects.i,
                    clim.sd=clim.sd.i, asp.mag=asp.mag.i, move.mx = move.mx.i,seeds = seeds.i,rho = rho.i,clim.dist = "runif")

df.unif = filter(df.unif,year>burn.in.yrs)

ggplot(df.unif,aes(x=clim))+
  geom_line(aes(y=`s_-1`,color="s-1"))+
  geom_line(aes(y=`s_0`,color="s0"))+
  geom_line(aes(y=`s_1`,color="s1"))+
  geom_point(aes(y=pop.lam,color="pop"))+
  theme_classic()+
  scale_color_manual(values=c("lightblue","black","salmon","goldenrod"))

```


###########################################################################################################################
###########################################################################################################################
######################################### Scratch and old code ############################################################

## Scenario 2: Exponential growth, symmetrical movement, Asymmetrical aspect effects
```{r Scen2}
# Things needed to run sim function line by line

# Sim. function inputs
burn.in.yrs <- 100
sim.yrs <- 500
asp.effects <- c(-2,1)
n.subpops <- length(asp.effects)
reps <- 10
clim.sds <- seq(0,20,by=1);clim.sds[clim.sds==0] <- 0.001
asp.mags <- seq(0,20,by=1)
rhos <- seq(0,0.5,0.25)

## Creating all combinations of movement rates
subpop.names = LETTERS[1:n.subpops] # Name subpops with letters
move.rates = seq(0,0.1,0.025)
move.dirs = expand.grid(from=subpop.names,to=subpop.names) %>% # get all combos
  # Remove rows that imply no movement (A to A)
  filter(from!=to) %>% 
   # Concatenate
  mutate(col.names = paste0(from,"to",to)) %>% 
  # save last column as a vector
  arrange(col.names) %>% pull() 

# Create movement data.frame to loop over
move.rates.df = matrix(data=rep(move.rates,length(move.dirs)),ncol=length(move.dirs)) %>% # generate matrix with movement rates
  as.data.frame() %>% 
  # Make all combos of movement rates
  expand.grid() %>% 
  filter(if_all(starts_with("V"),~ .==V1)) ## This filters for symmetrical movement rates
names(move.rates.df)=move.dirs # rename columns to make movement direction clear
rm(subpop.names,move.dirs,move.rates) # remove extra things from env

#### Run S1 #####
cl = makeCluster(20)
registerDoParallel(cl = cl)

S2_out_df <- foreach(rep = 1:reps, .combine = rbind,.packages=c("tidyverse","EnvStats")) %:% 
  foreach(move.rates.row = 1:nrow(move.rates.df), .combine = rbind,.packages=c("tidyverse","EnvStats")) %:%
    foreach(clim.sd.i = clim.sds, .combine = rbind,.packages=c("tidyverse","EnvStats")) %:%
      foreach(asp.mag.i = asp.mags, .combine = rbind,.packages=c("tidyverse","EnvStats")) %:% 
        foreach(rho.i = rhos,.combine = rbind,.packages=c("tidyverse","EnvStats")) %dopar% {

        move.rates.i <- move.rates.df[move.rates.row,]
        
        ##### Create a movement matrix from the move.rates row
        move.mx.i <- moveMx_fun(n.subpops,move.rates.i)
        
        seeds.i = seeds_df$avg.seeds[seeds_df$asp.mag==asp.mag.i]
        
        df = simfun_exponential(burn.in.yrs=burn.in.yrs, sim.yrs=sim.yrs, n.subpops=n.subpops,asp.effects = asp.effects,
                            clim.sd=clim.sd.i, asp.mag=asp.mag.i, move.mx = move.mx.i,seeds = seeds.i,rho = rho.i)
        
        tmp.df = df %>%
          filter(year>burn.in.yrs) %>% # Filter out burn-in years. This could also happen within the function.
          summarise(clim.mean = mean(clim),
                    clim.var = var(clim),
                    pop.var = var(pop.lam),
                    lt.pop.lam = geoMean(pop.lam),
                    sub.corr = cor(s1,s2)) %>% 
          mutate(clim.sd = clim.sd.i,
                 rho = rho.i,
                 asp.mag = asp.mag.i,
                 rep = rep,
                 asp.effects = list(asp.effects)) %>% 
          merge(.,move.rates.i)
        return(tmp.df)
      
        # rm(df,tmp.df,clim.sd.i,asp.mag.i,move.rate.i)
        
      }
stopCluster(cl)
write_csv(S2_out_df,paste0("SimOutput/S2_",round(Sys.time()),".csv"))
```


```{r}
plot_df <- S1_out_df %>% 
group_by(clim.sd,asp.mag,move.rate = AtoB,rho) %>% 
  summarize(agg.pop.var = mean(pop.var),
            mean.corr = mean(sub.corr,na.rm = T),
            agg.lt.pop.lam = mean(lt.pop.lam)) %>% 
  mutate(asp.effects = c("-1, +1"))

move.rates = c(0,0.04,0.1)

plot.breaks = seq(0.5,1.3,0.05)
neg.pal = brewer.pal(n = sum(plot.breaks<1),name = "YlOrBr")
pos.pal = brewer.pal(n = 9,name = "Blues")[5:9]
cols = c(rev(neg.pal),pos.pal)

```


```{r}
move.mx = moveMx_fun(2,data.frame(AtoB=0.01,BtoA=0.01))
asp.mag = 16
clim.sd = 12
seeds = seeds_df$avg.seeds[seeds_df$asp.mag==asp.mag]
out_df = NULL

df = simfun_exponential(burn.in.yrs=0,
                      sim.yrs=200,
                      n.subpops=n.subpops,
                      asp.effects = c(-1,1),
                      clim.sd=clim.sd,
                      asp.mag=asp.mag,
                      move.mx = move.mx,
                      seeds = seeds,
                      rho = 0)


# df <- filter(df,year>0)

ggplot(df,aes(x=s1,y=s2))+
  geom_point()+
  labs(title=paste0("Microhabitat effect strength = ",asp.mag,"\nClimate SD = ", clim.sd))
ggsave(h=8,w=8,filename = paste0("figs/clim",clim.sd,"_microhab",asp.mag,".png"))

clim.sds = seq(3,15,1)
out_df <- NULL
for(i in 1:length(clim.sds)){
  
  print(i)
  df = simfun_exponential(burn.in.yrs=0,
                        sim.yrs=500,
                        n.subpops=n.subpops,
                        asp.effects = c(-1,1),
                        clim.sd=clim.sds[i],
                        asp.mag=asp.mag,
                        move.mx = move.mx,
                        seeds = seeds,
                        rho = 0)
  
  out_df = rbind(out_df,df)
}

ggplot(out_df,aes(x=s1,y=s2))+
  geom_point()+
  facet_wrap(~clim.sd)

hist(rnorm(10000,0,6),breaks=50)

cor_df = out_df %>% 
  filter(clim.sd>0) %>% 
  group_by(clim.sd,asp.mag) %>% 
  summarize(cor = cor(s1,s2))

ggplot(cor_df,aes(x=clim.sd,y=cor))+
  geom_point()+
  geom_line()
```

```{r}
move.mx = moveMx_fun(2,data.frame(AtoB=0.01,BtoA=0.01))
asp.mag = 16
clim.sd = 12
seeds = seeds_df$avg.seeds[seeds_df$asp.mag==asp.mag]
out_df = NULL

df = simfun_exponential(burn.in.yrs=0,
                      sim.yrs=200,
                      n.subpops=n.subpops,
                      asp.effects = c(-1,1),
                      clim.sd=clim.sd,
                      asp.mag=asp.mag,
                      move.mx = move.mx,
                      seeds = seeds,
                      rho = 0)


# df <- filter(df,year>0)

ggplot(df,aes(x=s1,y=s2))+
  geom_point()+
  labs(title=paste0("Microhabitat effect strength = ",asp.mag,"\nClimate SD = ", clim.sd))
ggsave(h=8,w=8,filename = paste0("figs/clim",clim.sd,"_microhab",asp.mag,".png"))

clim.sds = seq(3,15,1)
out_df <- NULL
for(i in 1:length(clim.sds)){
  
  print(i)
  df = simfun_exponential(burn.in.yrs=0,
                        sim.yrs=500,
                        n.subpops=n.subpops,
                        asp.effects = c(-1,1),
                        clim.sd=clim.sds[i],
                        asp.mag=asp.mag,
                        move.mx = move.mx,
                        seeds = seeds,
                        rho = 0)
  
  out_df = rbind(out_df,df)
}

ggplot(out_df,aes(x=s1,y=s2))+
  geom_point()+
  facet_wrap(~clim.sd)

hist(rnorm(10000,0,6),breaks=50)

cor_df = out_df %>% 
  filter(clim.sd>0) %>% 
  group_by(clim.sd,asp.mag) %>% 
  summarize(cor = cor(s1,s2))

ggplot(cor_df,aes(x=clim.sd,y=cor))+
  geom_point()+
  geom_line()
```

```{r}
prism <- read_csv("~/Desktop/prism.csv")
hist(prism$temp,breaks=30)
hist(df$clim,breaks=30)
```


## adding in climate autocorrelation
```{r}
rm(list=ls())
years <- 1000
clim.sd <- 20
rho <- 0.5
beta <- sqrt(1-rho^2)
e_old <- rnorm(1,mean=0,sd=clim.sd)

clims <- data.frame(year = 1:years,
                    clim.cor = NA)


for(i in 1:years){
  # 
  # # Generate new value based on previous value and random noise
  z_t <- rnorm(1)
  e_new <- rho*e_old + clim.sd*beta*z_t
  clims$clim.cor[i] <- e_new
  e_old <- e_new;rm(e_new)  
  
}

ggplot(clims,aes(x=year))+
  geom_point(aes(y=clim.cor))+
  geom_line(aes(y=clim.cor))

sd(clims$clim.cor)

####
e_old.AR1 <- e_old.log <- rnorm(1,mean=0,sd=clim.sd)


a <- arima.sim(n=100, list(ar=c(0.5)))
b <- arima.sim()
plot(a)

ar_sd1 <- arima.sim(n = 100, list(ar = 0.5), sd = 1)
ar_sd10 <- arima.sim(n = 100, list(ar = 0.5), sd = 10)
x <- arima.sim(model = list(ar=0.1), n = 100)
plot(x)


  

ggplot(clims,aes(x = years))+
  geom_line(aes(y=clim,color="clim"),linewidth=1,alpha=0.5)+
  geom_point(aes(y=clim,color="clim"),alpha=0.5)+
  geom_line(aes(y=clim.cor.AR1,color="AR1"))+
  geom_point(aes(y=clim.cor.AR1,color="AR1"))+
  geom_line(aes(y=clim.cor.log,color="log"))+
  geom_point(aes(y=clim.cor.log,color="log"))+
  ggthemes::theme_clean()+
  scale_color_manual(values=c("salmon2","black","dodgerblue"))

ggplot(clims)+
  geom_histogram(aes(x=clim),fill="grey50",color="black",alpha=0.25)+
  geom_histogram(aes(x=clim.cor.AR1),fill="salmon",color="black",alpha=0.5)

# Simulation loop for AR(1) process
for (i in 2:years) {
  
  # Generate new value based on previous value and random noise
  epsilon_t <- rnorm(1, mean = 0, sd = clim.sd)
  clims$clim.cor[i] <- rho * clims$clim.cor[i - 1] + epsilon_t

}

rm(list = ls())

# Start with an initial value for both autocorrelated and uncorrelated values
clims$clim.cor[1] <- rnorm(1, mean = 0, sd = clim.sd)  # Autocorrelated start
clims$clim.uncor[1] <- rnorm(1, mean = 0, sd = clim.sd)  # Uncorrelated start

# Simulation loop for AR(1) process (autocorrelated values)
for (i in 2:years) {
  
  # Generate new value for autocorrelated climate
  epsilon_t <- rnorm(1, mean = 0, sd = clim.sd)
  clims$clim.cor[i] <- rho * clims$clim.cor[i - 1] + epsilon_t
  
  # Generate new value for uncorrelated climate (random draw)
  clims$clim.uncor[i] <- rnorm(1, mean = 0, sd = clim.sd)
}


# Reshape data for ggplot
clims_long <- reshape2::melt(clims, id.vars = "years", 
                             variable.name = "clim_type", 
                             value.name = "clim_value")

# Plot with ggplot
ggplot(clims_long, aes(x = years, y = clim_value, color = clim_type)) +
  geom_line() +
  labs(title = "Comparison of Autocorrelated and Uncorrelated Climate Values",
       y = "Climate Value", x = "Year") +
  scale_color_manual(values = c("blue", "red"),
                     labels = c("Autocorrelated (rho = 0.5)", "Uncorrelated")) +
  theme_minimal() +
  theme(legend.title = element_blank(), 
        legend.position = "top")



```

