---
title: "CompareScenarios"
author: "Claire Powers"
date: "2025-01-13"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r pacakges_plotthemes, include=FALSE}
library(tidyverse)
library(pals)
library(randomcoloR)
library(scico)
library(RColorBrewer)

rm(list=ls())

plot_theme <- function() {
  theme(
    panel.border = element_rect(colour = "black", fill = NA, linetype = 1),
    panel.background = element_rect(fill = "white"),
    strip.background = element_rect(fill="white",color="black"),
    panel.grid.major.y = element_line(colour = "gray80", linetype = 3, linewidth = 0.5),
    panel.grid.minor.y = element_blank(),# element_line(colour = "gray90", linetype = 3, linewidth = 0.5),
    panel.grid.major.x =  element_line(colour = "gray80", linetype = 3, linewidth = 0.5),
    panel.grid.minor.x = element_blank(),# element_line(colour = "gray90", linetype = 3, linewidth = 0.5)
    axis.text = element_text(size=12),
    axis.title = element_text(size=13),
    legend.text = element_text(size=12),
    legend.title = element_text(size=13),
    title = element_text(size=14)
  )
}

binwidth = 0.1
contour_colors <- function(df,binwidth,var){
  
  if(var=="lambda"){
    
    limits <- round(max(abs(1 - df$pop.lam)) * c(-1, 1) + 1,1)
    breaks <- seq(min(limits),max(limits),by=binwidth)
    pal <- scico(n = length(breaks),palette = "vik",direction = -1)
    
  } else if(var=="variance"){
    
    limits <- round(max(abs(1 - df$agg.pop.var)) * c(-1, 1) + 1,1)
    breaks <- seq(min(limits),max(limits),by=binwidth)
    pal <- colorRampPalette( brewer.pal(9,"Spectral") )(length(breaks)) 
    # scico(n = length(breaks),palette = "vik",direction = -1)
  } else {print("no valid variable provided")}
  
  
  ### Code for different options ###
  # colorRampPalette( brewer.pal(9,"RdYlGn") )(length(breaks))
  # brewer.spectral(n = length(breaks))
  
  }

```

```{r data, include=FALSE}

# All responses reflect mean climate (a.e. = -1,1)
S0 <- read_csv("SimOutput/asp_effect_output/aspeff_-1,1_2025-01-13.csv") %>% 
  group_by(clim.sd, asp.mag, move.rate, rho, asp.effect) %>%
  summarize(agg.pop.var = mean(pop.var),
            pop.lam = mean(lt.pop.lam),
            .groups="drop")

# Aspect effect = -2,1
S1 <- read_csv("SimOutput/asp_effect_output/aspeff_-2,1_2025-01-13.csv") %>% 
  group_by(clim.sd, asp.mag, move.rate, rho, asp.effect) %>%
  summarize(agg.pop.var = mean(pop.var),
            pop.lam = mean(lt.pop.lam),
            .groups="drop")
```

#### Looking at basic dynamics

1. How do long term population growth rates compare for these three scenarios, across microhabitat effect strengths and climate standard deviations?
```{r lt.lam.compare}

rho.i = 0
move.rate.i = c(0,0.05,0.1)

S0_plot <- filter(S0,rho==rho.i & move.rate %in% move.rate.i)
S1_plot <- filter(S1,rho==rho.i & move.rate %in% move.rate.i)

lam_plot <- rbind(S0_plot,S1_plot) %>% 
  mutate(asp.effect = factor(asp.effect,levels=c("0","-101","-11")))

cols = contour_colors(df=lam_plot,binwidth = 0.05,var="lambda")

s0_ltlam <- ggplot(S0_plot,aes(x=clim.sd,y=asp.mag,z=pop.lam))+
  geom_contour_filled()+
  scale_fill_manual(values=cols)+
  labs(x="Climate SD",y="Microhabitat effect strength",fill="LT lambda",title="Microhabitat effects = c(-1,1)")+
  theme_bw(base_size=14)+
  facet_wrap(~move.rate);s0_ltlam

s1_ltlam <- ggplot(S1_plot,aes(x=clim.sd,y=asp.mag,z=pop.lam))+
  geom_contour_filled()+
  scale_fill_manual(values=cols)+
  labs(x="Climate SD",y="Microhabitat effect strength",fill="LT lambda",title="Microhabitat effects = c(-2,1)")+
  theme_bw(base_size=14)+
  facet_wrap(~move.rate);s1_ltlam

cowplot::plot_grid(s0_ltlam,s1_ltlam,ncol=1)

## Something is wrong here. Look at output first, but then consider what is happening with the aspect magnitudes. 
```

## Variance
```{r}

cols = contour_colors(df=S0_plot, binwidth = 0.05, var="variance")

s0_var <- ggplot(S0_plot,aes(x=clim.sd,y=asp.mag,z=agg.pop.var))+
  geom_contour_filled(binwidth = 0.05)+
  scale_fill_manual(values=cols)+
  labs(x="Climate SD",y="Microhabitat effect strength",fill="Variance in LT lambda",title="Microhabitat effects = c(0)")+
  theme_bw(base_size=14)+
  facet_wrap(~move.rate);s0_var

s1_var <- ggplot(S1_plot,aes(x=clim.sd,y=asp.mag,z=agg.pop.var))+
  geom_contour_filled(binwidth=0.05)+
  scale_fill_manual(values=cols)+
  labs(x="Climate SD",y="Microhabitat effect strength",fill="Variance in LT lambda",title="Microhabitat effects = c(0)")+
  theme_bw(base_size=14)+
  facet_wrap(~move.rate);s1_var


cowplot::plot_grid(s0_var,s1_var,ncol=1)

```

#### 



