---
title: "Manuscript Figures"
author: "Claire Powers"
date: "2024-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r start}
rm(list=ls())

# Packages
library(tidyverse)
library(parallel)
library(doParallel)
library(foreach)
library(EnvStats)

# Plotting
theme_set(theme_bw(base_size=14))
stage.cols = c(seed="springgreen4",juv="blue3",flrg="magenta3")
place.cols = c(Cooler ="#175D71" , Warmer = "#98463C", Avg = "#D48B47")

# Constants
sizes = c(seed=1,juv=8,flrg=10)

# Functions 
source("ModelFunctions/ParamVals.R")
source("ModelFunctions/logit2prob.R")
source("ModelFunctions/survival_fun.R")
source("ModelFunctions/growth_fun.R")
source("ModelFunctions/subpop_mx_fun.R")
source("ModelFunctions/seednum_fun.R")
seed_df <- read_csv("seedSearchOutput/seedSearch_2025-01-29 21:30:11.114866.csv") %>% 
  mutate(seeds2 = floor(seeds)) %>% 
  group_by(asp.effects,clim.sd,asp.mag) %>% 
  summarize(avg.seeds = round(mean(seeds)))
```

## Figure 2. No, med, high asp effect demo
```{r}

asp.effects = c(-1,1)
n.subpops = length(asp.effects)
start.cells = seq(1,n.subpops*3,by=3)

lam_df = expand.grid(asp.mag = c(1,5,10,15),
                     clim = seq(-40,40,1),
                     s1 = NA, s2 = NA, pop=NA)

for(i in 1:nrow(lam_df)){
  
  pop.mx = matrix(0,nrow=3*n.subpops,ncol=3*n.subpops)
  
  growth_params.i <- growth_params;surv_params.i <- surv_params
  growth_params.i$clim <- surv_params.i$clim <- lam_df$clim[i]
  growth_params.i$asp.mag <- surv_params.i$asp.mag <- lam_df$asp.mag[i]
  seeds.i <- seed_df$avg.seeds[asp.mag = lam_df$asp.mag[i]] %>% round()
  
  for(j in 1:n.subpops){
    
    growth_params.i$asp.effect <- surv_params.i$asp.effect <- asp.effects[j]
    sub.mx = subpop_mx_fun(surv_params = surv_params.i,growth_params = growth_params.i,seeds.in = seeds.i)
    lam_df[i,paste0("s",j)] <- Re(eigen(sub.mx)$values[1])
    
    pop.mx[start.cells[j]:(start.cells[j] + 2),start.cells[j]:(start.cells[j] + 2)] <- sub.mx
    
  }
  
  lam_df$pop[i] <- Re(eigen(pop.mx)$values[1])
  
}

ggplot(lam_df,aes(x=clim))+
  annotate("rect", xmin=-20, xmax=20, ymin=-Inf, ymax=Inf, alpha=0.2, fill="grey70")+
  geom_line(aes(y=s1,color="-1"),linewidth = 1)+
  geom_line(aes(y=s2,color="+1"),linewidth = 1)+
  theme_bw(base_size = 16)+
  scale_x_continuous(limits = c(-40,40))+
  # theme(legend.position = "none")+
  labs(title=paste0("Microhabitat conditions relative to regional average (0) = ",list(asp.effects)))+
  facet_wrap(~asp.mag,ncol=2)+
  scale_color_manual(values = c("dodgerblue","sienna2"))


lam_df2 <- lam_df %>% 
  filter(clim>-21 & clim <21) %>% 
  group_by(asp.mag) %>% 
  mutate(corr = cor(s1,s2))

asp.mags = seq(1,20,5)
clim.sds = seq(5,20,5)

for(x in 1:clim.sds){
  for(y in 1:asp.mags){
          
        lam_df = expand.grid(asp.mag = asp.mags[y],
                     clim = seq(-50,50,1),
                     s1 = NA, s2 = NA, pop=NA)
    
        for(i in 1:nrow(lam_df)){
      
          growth_params.i <- growth_params;surv_params.i <- surv_params
          growth_params.i$clim <- surv_params.i$clim <- lam_df$clim[i]
          growth_params.i$asp.mag <- surv_params.i$asp.mag <- lam_df$asp.mag[i]
          seeds.i <- seed_df$avg.seeds[asp.mag = asp.mags[y]] %>% round()
          
          pop.mx = matrix(0,nrow=3*n.subpops,ncol=3*n.subpops)
    
          for(j in 1:n.subpops){
            
            growth_params.i$asp.effect <- surv_params.i$asp.effect <- asp.effects[j]
            sub.mx = subpop_mx_fun(surv_params = surv_params.i,growth_params = growth_params.i,seeds.in = seeds.i)
            lam_df[i,paste0("s",j)] <- Re(eigen(sub.mx)$values[1])
            
            pop.mx[start.cells[j]:(start.cells[j] + 2),start.cells[j]:(start.cells[j] + 2)] <- sub.mx
            
          }
      
          lam_df$pop[i] <- Re(eigen(pop.mx)$values[1])
          
        }
    
    lams <- ggplot(lam_df,aes(x=clim))+
      geom_line(aes(y=s1,color="s1"))+
      geom_line(aes(y=s2,color="s2"))+
      ggthemes::theme_clean()+
      scale_x_continuous(limits = c(-40,40))+
      theme(legend.position = "none")+
      labs(title=paste0("Aspect mag = ",asp.mags[asp.mag]))
    
    hist <- ggplot(data=data.frame(clim=rnorm(10^6,0,clim.sds[clim.sd])),aes(x=clim))+
      geom_density(fill="grey75",color="black")+
      scale_x_continuous(limits = c(-40,40))+
      #theme(axis.text = element_blank())+
      labs(title = paste0("Clim SD = ",clim.sds[clim.sd]))+
      ggthemes::theme_clean()
    
    cowplot::plot_grid(lams,hist,ncol=1)
    ggsave(h=10,w=7,filename = paste0("climhist_response_figs/clim",clim.sds[clim.sd],"_hab",asp.mags[asp.mag],".png"))
    
  }
}

lams <- ggplot(filter(lam_df,asp.mag==12),aes(x=clim))+
  geom_line(aes(y=s1,color="s1"))+
  geom_line(aes(y=s2,color="s2"))+
  ggthemes::theme_clean()+
  scale_x_continuous(limits = c(-40,40))+
  theme(legend.position = "none")+
  labs(title="Aspect mag = 12")

hist <- ggplot(data=data.frame(clim=rnorm(10^6,0,10)),aes(x=clim))+
  geom_density(fill="grey75",color="black")+
  scale_x_continuous(limits = c(-40,40))+
  #theme(axis.text = element_blank())+
  labs(title = "Clim SD ")+
  ggthemes::theme_clean()

cowplot::plot_grid(lams,hist,ncol=1)
```


#### Look at survival fun across range of clim var, asp.eff, asp.mag ####
```{r more_survivalFun}

surv_df = expand.grid(asp.effect = c(-1,1),
                      asp.mag = c(1,10,20),
                      clim = seq(-40,40,1),
                      seed = NA, juv = NA,flrg=NA)

for(i in 1:nrow(surv_df)){

  surv_df[i,c('seed','juv',"flrg")] =
    survival_fun(sizes = surv_params$sizes,
                 max.survival.rates = surv_params$max.survival.rates,
                 min.survival.rates = surv_params$min.survival.rates,
                 S_2 = surv_params$S_2,
                 S_3 = surv_params$S_3,
                 asp.mag = surv_df$asp.mag[i],
                 asp.effect = surv_df$asp.effect[i],
                 clim = surv_df$clim[i])

}

surv_df = surv_df %>%
  mutate(place.name = case_when(asp.effect==-1~"Cooler",
                                asp.effect==1~"Warmer"))

ggplot(surv_df,aes(x=clim,y=juv,color=place.name))+
  geom_line(linewidth=1)+
  geom_vline(xintercept=0)+
  facet_wrap(~asp.mag, labeller = labeller(asp.mag = c('1'="weak", '10' = "mid",'20' = 'strong'))) +
  theme_bw(base_size = 18)+
  scale_color_manual(values=place.cols)+
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank())+
  labs(x="Climate", y = "Performance",color="Microhabitat\neffect")

```



